# Base configs
baseurl: "https://sarthakswaroop.github.io
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Sarthak Swaroop Bansal"
subtitle: "See the world through my perspective"
author: "Sarthak Swaroop Bansal"
header:
 title: "Photography"
 subtitle: "by Sarthak Swaroop Bansal"
footer:
 name: "Hey there, my name is Sarthak"
 bio: "I am a self taught developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/ram_patra"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/rampatra"
